const BANK={
  4:{
    easy:'ABLE AREA BABY BACK BALL BAND BANK BASE BATH BEAR BEAT BELL BEST BIRD BLUE BOAT BODY BOOK BORN BOTH CAMP CARD CARE CITY CLUB COAT COLD DARK DOOR DOWN DRAW DROP EASY FACE FACT FARM FAST FEAR FEEL FIRE FISH FOOD FOOT GAME GIFT GIRL GIVE GOLD GOOD HAIR HALF HAND HARD HAVE HEAD HELP HOME HOPE IDEA KEEP KIND KING KNOW LAND LAST LIFE LIKE LINE LIST LIVE LONG LOOK LOVE MAKE MANY MEAL MEET MIND MORE MOVE NAME NEAR NEED NEWS NEXT NICE OPEN PAGE PAIR PARK PART PLAY RAIN READ REAL REST RIDE ROAD ROCK ROOM RULE SAFE SAME SHOP SHOW SIDE SING SKIN SNOW SONG STAR STAY STOP TALK TEAM TIME TREE TRUE TURN WALK WALL WANT WARM WASH WEEK WELL WEST WIND WISH WORD WORK YEAR',
    normal:'ARCH AXIS BARK BEAM BEND BITE BOLD BOND BOOM BOOT BOWL BULK BURN CAGE CALM CAST CHAT CHIP CLAY CLIP CODE COIN COOL CORE CROP DARE DAWN DEEP DESK DIVE DOCK DRUM DUST EDGE ELSE EVEN FAIR FALL FILE FIRM FLAG FLAT FLOW FOLD GAIN GEAR GLOW GOAL GRAB GRAY GROW HALL HILL HIRE HOLD HUNT JOIN JUMP KICK LACK LAKE LEAD LEAF LEFT LINK LOAD LOAN LOST LOUD LUCK MAIL MARK MEAN MILK MOON NAIL NAVY NEST NOTE PACK PATH PEAK PINK POOL PORT POST PULL PURE RACE RAIL RATE RING RISE ROLL ROOF ROOT ROSE RUSH SALT SAND SEAT SEED SHIP SHOE SOFT SOUL SPIN SPOT STEP SUIT TALL TAPE TASK TENT TINY TOOL TOUR TOWN TYPE USER VAST VIEW WAVE WIDE WILD WINE WING WIRE WOOD ZONE',
    hard:'ABYS AEON AGUE ALOE AMOK APEX AQUA ARID BALE BANE BARD BASK BIDE BOON BOUT BRIM BUOY BURL BYRE CASK CHUM CLOD CUSP DALE DAUB DOUR DREG DYAD EDDY EMIR ETCH FIEF FLAX FUME GAIT GILT GNAT GOAD GOUT GYRE HAZE HEWN HILT IBEX ICON IDOL IMAM JADE JEST JUTE KILN LARD LILT LODE LOOM LURE LYNX MACE MALT MICA MIRE NARY NEWT NOOK OATH OGRE PACT PITH PLOY PORE PROD QUAY RIFT RIND RUNE SAGE SEAR SKEW SLAG SLOE SMEL SNAG TARE TERN THUD TOME TORE VANE VEIL WANE WARY WELT WHIM WISP YOKE ZEAL ZINC'
  },
  5:{
    easy:'ABOUT ABOVE AFTER AGAIN APPLE BEACH BLACK BRAIN BREAD BROWN CHAIR CHILD CLEAN CLEAR CLOCK CLOUD DANCE DREAM DRINK EARTH ENJOY FAITH FIELD FIRST FLAME FLOOR FOCUS FORCE FRAME FRESH FRUIT FUNNY GHOST GIANT GLASS GRAPE GREAT GREEN GROUP GUESS HAPPY HEART HONEY HORSE HOUSE IMAGE LARGE LEARN LEMON LIGHT LUCKY MAGIC MAJOR MARCH MATCH MAYBE MODEL MONEY MONTH MOUSE MOVIE MUSIC NIGHT NURSE OCEAN PAINT PANDA PAPER PARTY PEACE PHONE PIANO PLACE PLANE PLANT POINT POWER PRICE QUEEN QUICK QUIET RADIO RIGHT RIVER ROBOT ROUND SHEEP SHORT SMILE SMART SNAKE SOLAR SORRY SOUND SOUTH SPACE SPORT STAGE START STONE STORY STORM SUGAR TABLE TEACH THING THINK THREE TIGER TODAY TOWER TRAIN UNDER VALUE VIDEO VOICE WATCH WATER WHEEL WHITE WOMAN WORLD WRITE YOUNG',
    normal:'ACTOR ADULT ALARM ALBUM ANGEL ANGER AWARD BASIC BLIND BLOCK BOARD BOUND BRAVE BRICK CARRY CAUSE CHARM COAST COUNT COURT COVER CRAZY CROWN DAILY DRIVE ENTER EQUAL EXTRA FALSE FEVER FINAL FIXED FLASH FLEET FLOAT FRONT GIVEN GRADE GRAND GRASS HEAVY IDEAL KNIFE LAYER LEVEL LOCAL METAL MIGHT MOTOR MOUNT MOUTH NAKED NOISE NORTH NOVEL OFFER OFTEN ORDER OTHER OWNER PANEL PHASE PIECE PILOT PITCH PRIDE PRIME PROOF RAISE REACH ROUGH ROUTE ROYAL SCALE SCORE SERVE SHAPE SHIFT SHOCK SIGHT SINCE SKILL SLEEP SMALL SMOKE SOLID SPEED SPEND SPLIT SPOKE STAND STEAM STEEL STICK STILL STOCK SWEET TEETH THEME THROW TOTAL TOUCH TOUGH TRACK TRADE TREND TRUCK TRUST TRUTH TWICE UNION UNITY UPPER USUAL VISIT WASTE WHOLE WORRY WORTH WRONG',
    hard:'ABACK ABATE ABBEY ABHOR ABYSS ACORN ADAGE ADEPT ADOBE AGLOW ALOFT AMBER AMBLE AMISS AMONG ANVIL AORTA APRON ARBOR ARDOR AUGUR AVERT AZURE BARGE BASTE BEECH BELLE BERTH BIRCH BLAND BLEAK BLITZ BLOKE BLUFF BLUNT BRAID BRINE BRISK BROOD BRUNT CABAL CACAO CAIRN CHAFF CHASM CHIDE CHURN CLIQUE COLON CRONE CURIO DECOY DELTA DITTO DOWEL DROLL EERIE ELATE ETHOS EXALT FABLE FARCE FERAL FJORD FLASK FORTE GAUZE GUILE HAVEN HINGE HOIST INERT INLET JAUNT KNEAD KNOLL LADEN LATCH LUCID MANGE MANOR MERIT NICHE NYMPH OAKEN OMBRE OPINE OXIDE PERCH PETAL PLUME QUELL REBUS RIVET ROGUE SAUNA SHARD SIEVE SKIFF SLOTH SNIDE STOIC SWATH TANGO TAWNY THYME TRYST USURP VIGOR WALTZ WHARF WREAK YEARN'
  },
  6:{
    easy:'ACTION ALWAYS ANIMAL ANSWER AUTUMN BEAUTY BECOME BEFORE BETTER BRIGHT CAMERA CHANGE CHOICE CHURCH CIRCLE COMMON CORNER COURSE DINNER DOCTOR DREAMS DRIVER FAMILY FATHER FRIEND FUTURE GARDEN GOLDEN GROUND GROWTH HEALTH ISLAND LETTER LITTLE MARKET MIDDLE MINUTE MOTHER NATURE OFFICE PEOPLE PERSON PLANET PLAYER PRETTY SCHOOL SIMPLE SISTER STREET STRONG SUMMER THINGS TRAVEL WINDOW WINTER WONDER YELLOW',
    normal:'ADVICE ALMOST AMOUNT ARCADE ARTIST AUTHOR BATTLE BORDER BOTTLE BRANCH BRIDGE BUDGET BUTTON CAREER CENTER CHANCE CHARGE CREATE DANGER DEALER DEGREE DESIGN DIRECT DOUBLE EFFORT ENGINE ESCAPE FABRIC FINISH FLIGHT FLOWER FOREST FORWARD GLOBAL HANDLE HAPPEN HEIGHT HONEST INCOME INSIDE JOURNEY LEADER LEAGUE LEAVES LEGEND MASTER MEMORY MODERN MOMENT NATION NATIVE NORMAL NOTICE OBJECT OPTION ORANGE PARENT PERIOD POCKET POLICE PROFIT PUBLIC REASON RECORD REGION RESULT SAFETY SEARCH SECRET SHADOW SIGNAL SINGLE SOURCE SPEECH SPRING SQUARE STATUS SYSTEM TARGET THEORY TICKET UNIQUE VALLEY VISION VOLUME',
    hard:'ABACUS ABLAZE ACUMEN ADRIFT ALCOVE ANVILS APLOMB ARCANE AUBURN AURORA BAUBLE BEACON BEFALL BELLOW BODICE BREACH BRIDLE BYGONE CANTER CIPHER COBALT CORPUS CRAVAT CUDDLE CURDLE DABBLE DAINTY DEARTH DOCILE DULCET ENIGMA FACADE FATHOM FERRET FIASCO FLAUNT FODDER FORAGE FRESCO GAMBIT GOBLET GROTTO GYPSUM HAGGLE IMPISH JARGON JOSTLE LACUNA MAROON MEADOW MINGLE MURMUR NECTAR OBLONG ORACLE PALLET PEBBLE PIGEON QUARRY QUENCH QUIVER RANCOR RELISH RIDDLE SAVANT SCYTHE SLEUTH TUNDRA VELLUM WRAITH ZEALOT ZEPHYR'
  },
  7:{
    easy:'ANOTHER BALANCE BECAUSE BEDROOM BELIEVE BROTHER CAPITAL CAREFUL CENTURY CERTAIN CHICKEN COUNTRY DIAMOND EVENING EXAMPLE FARMERS FOREVER GENERAL GOODBYE HEALTHY HOLIDAY HOSPITAL HUNDRED HUSBAND KITCHEN LIBRARY MACHINE MORNING NATURAL NOTHING OUTSIDE POPULAR PROBLEM PRODUCT PROGRAM QUICKLY RAINBOW READING SCIENCE SPECIAL STUDENT SUCCESS TEACHER THOUGHT THROUGH TONIGHT VILLAGE WEATHER WEEKEND WELCOME WITHOUT',
    normal:'ACHIEVE ADDRESS AIRPORT ARTICLE ATTEMPT ATTRACT AVERAGE BATTERY BENEATH BENEFIT CABINET CAPTAIN CENTRAL CHAPTER CHARITY CLIMATE CLOTHES COLLECT COLLEGE COMFORT COMMAND COMPANY COMPARE COMPLETE CONCERT CONNECT CONTROL CORRECT CULTURE CURRENT DECIDE DEVELOP DIGITAL DISCUSS DISTANT DRAWING EARNING EASTERN ECONOMY EDITION ELEMENT EXCITED EXPLAIN FACTORY FEATURE FREEDOM HISTORY IMPROVE INCLUDE JUSTICE LEADING MANAGER MEETING MESSAGE MISSING OFFICER OPINION PATIENT PAYMENT PERFECT PROJECT PROTECT REALITY RECEIVE SECTION SERIOUS SERVICE SHARING SIMILAR SOCIETY STATION SUPPORT VICTORY VIRTUAL WAITING',
    hard:'ABJURED ANODYNE APHELIA ARCHAIC ASCETIC BUCOLIC CADENCE CALIPER CAPRICE CATHODE CITADEL COUTURE CUNNING DEBACLE ELYSIAN ERRATIC FLUMMOX GOSSAMER HIRSUTE IMPETUS LACONIC MAGENTA MALAISE MANDIBLE MEMENTO OBELISK PALADIN PANACEA PENSIVE PLACATE QUASARS RADIANT SALIENT SCARABS TACTILE TIRADES TRIDENT VERDANT VORTEXES'
  },
  8:{
    easy:'AIRPLANE ANYTHING BIRTHDAY BUILDING BUSINESS CHILDREN COMPUTER DIFFERENT DINOSAUR EVERYONE FAVORITE FOOTBALL FRIENDLY LANGUAGE LEARNING MAGAZINE MOUNTAIN QUESTION REMEMBER SENTENCE SHOPPING SUNSHINE SWIMMING TOGETHER TOMORROW VACATION',
    normal:'ABSOLUTE ABSTRACT ACCIDENT ACCURATE ACTIVITY ACTUALLY ADVANCED AIRCRAFT ALPHABET ANALYSIS APPROACH ARGUMENT ATTITUDE AUDIENCE BASEBALL BEAUTIFUL BOUNDARY CAMPAIGN CATEGORY CHAMPION CHEMICAL CREATIVE CULTURAL CUSTOMER DECISION DELIVERY DISCOVER DISTANCE DOCUMENT DOMESTIC EDUCATION ELECTION EMOTIONAL ENGINEER EXCHANGE EXERCISE FAMILIAR FINANCIAL FUNCTION GENEROUS HISTORIC IDENTITY INDUSTRY MATERIAL MEDICINE MOVEMENT NATIONAL ORIGINAL PERSONAL PLATFORM POSITION PRACTICE PRESSURE PROPERTY RESEARCH RESOURCE RESPONSE SECURITY STANDARD STRATEGY STRENGTH THOUSAND TRAINING TRANSFER VARIABLE',
    hard:'ABERRANT APERTURE ARBOREAL CALDERAS CHIMERIC CLEMENCY COGNATES COVALENT DIATRIBE DILATORY ENDEMIC FIDELITY GARRISON HEDONISM INCIPIENT INDOLENT LIMERICK LUMINARY MERIDIAN NEOPHYTE PARALLAX PHOENIXS QUANDARY QUOTIENT RECONDITE RESONANT TENACIOUS VERACITY'
  }
};

for(const length in BANK)for(const level in BANK[length])BANK[length][level]=BANK[length][level].split(/\s+/).filter(word=>word.length===Number(length));
const labels={easy:'简单',normal:'普通',hard:'困难'};
let length=5,difficulty='normal',answer='',row=0,guess='',over=false;
const board=document.querySelector('#board'),keyboard=document.querySelector('#keyboard'),message=document.querySelector('#message');
const lengthSelect=document.querySelector('#wordLength'),difficultySelect=document.querySelector('#difficulty');

function start(){
  length=Number(lengthSelect.value);difficulty=difficultySelect.value;
  const pool=BANK[length][difficulty];answer=pool[Math.floor(Math.random()*pool.length)];
  row=0;guess='';over=false;message.textContent='';board.innerHTML='';keyboard.innerHTML='';
  board.style.setProperty('--letters',length);board.style.setProperty('--board-width',`${Math.min(500,length*66)}px`);
  document.querySelector('#subtitle').textContent=`6 次机会，猜出 ${length} 个字母的英文单词 · ${labels[difficulty]}（${pool.length} 词）`;
  for(let r=0;r<6;r++){const el=document.createElement('div');el.className='row';for(let c=0;c<length;c++){const tile=document.createElement('div');tile.className='tile';el.append(tile)}board.append(el)}
  makeKeyboard();
}

function makeKeyboard(){['QWERTYUIOP','ASDFGHJKL','↵ZXCVBNM⌫'].forEach(chars=>{const keyRow=document.createElement('div');keyRow.className='key-row';[...chars].forEach(ch=>{const key=document.createElement('button');key.className='key'+('↵⌫'.includes(ch)?' wide':'');key.textContent=ch==='↵'?'提交':ch==='⌫'?'删除':ch;key.dataset.key=ch;key.onclick=()=>input(ch);keyRow.append(key)});keyboard.append(keyRow)})}
function input(key){if(over)return;if(key==='⌫'){guess=guess.slice(0,-1);paint()}else if(key==='↵')submit();else if(guess.length<length){guess+=key;paint()}}
function paint(){[...board.children[row].children].forEach((tile,i)=>{tile.textContent=guess[i]||'';tile.className='tile'+(guess[i]?' filled':'')})}
function toast(text){message.innerHTML=`<span class="toast">${text}</span>`;setTimeout(()=>message.textContent='',1900)}
function submit(){
  if(guess.length<length)return toast(`还需要 ${length-guess.length} 个字母`);
  const states=Array(length).fill('absent'),left={};
  [...answer].forEach((letter,i)=>{if(guess[i]===letter)states[i]='correct';else left[letter]=(left[letter]||0)+1});
  [...guess].forEach((letter,i)=>{if(states[i]!=='correct'&&left[letter]){states[i]='present';left[letter]--}});
  [...board.children[row].children].forEach((tile,i)=>setTimeout(()=>{tile.className=`tile reveal ${states[i]}`;const key=document.querySelector(`[data-key="${guess[i]}"]`);if(key&&!key.classList.contains('correct')&&(states[i]==='correct'||!key.classList.contains('present')))key.className=`key ${states[i]}`},i*150));
  const won=guess===answer;
  setTimeout(()=>{if(won){over=true;toast('太棒了！猜对了 🎉');save(true)}else if(++row===6){over=true;toast(`答案是 ${answer}`);save(false)}guess=''},length*150+400);
}

function getStats(){return JSON.parse(localStorage.getItem('wordleStatsV2')||'{"played":0,"won":0,"streak":0,"best":0}')}
function save(won){const stats=getStats();stats.played++;if(won){stats.won++;stats.streak++;stats.best=Math.max(stats.best,stats.streak)}else stats.streak=0;localStorage.setItem('wordleStatsV2',JSON.stringify(stats))}
document.addEventListener('keydown',event=>{if(event.key==='Enter')input('↵');else if(event.key==='Backspace')input('⌫');else if(/^[a-z]$/i.test(event.key))input(event.key.toUpperCase())});
document.querySelector('#newGame').onclick=start;
const modal=document.querySelector('#modal'),content=document.querySelector('#modalContent');
document.querySelector('#close').onclick=()=>modal.close();
document.querySelector('#help').onclick=()=>{content.innerHTML='<h2>怎么玩</h2><p>先选择单词长度和难度，再用 6 次机会猜出答案。</p><div class="example"><span class="mini correct">W</span><span class="mini">O</span><span class="mini">R</span><span class="mini">D</span></div><p><b>绿色</b>：字母和位置都正确</p><p><b>黄色</b>：单词中有这个字母，但位置不对</p><p><b>灰色</b>：单词中没有这个字母</p><p>简单是高频词，普通是常用进阶词，困难包含较生僻词汇。</p>';modal.showModal()};
document.querySelector('#stats').onclick=()=>{const stats=getStats();content.innerHTML=`<h2>统计</h2><div class="stat-grid"><div class="stat"><strong>${stats.played}</strong><span>场次</span></div><div class="stat"><strong>${stats.played?Math.round(stats.won/stats.played*100):0}</strong><span>胜率 %</span></div><div class="stat"><strong>${stats.streak}</strong><span>连胜</span></div><div class="stat"><strong>${stats.best}</strong><span>最佳</span></div></div><div class="actions"><button class="primary" id="again">再玩一局</button></div>`;modal.showModal();document.querySelector('#again').onclick=()=>{modal.close();start()}};
start();
